In [1]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from sklearn.metrics import accuracy_score

#Librerias para visualizacion
import seaborn as sb
import matplotlib.pyplot as plt

In [2]:
labels_training = pd.read_csv('D:/DATOS/RELOADED/csv/labels_training_set.csv',
                              low_memory= False)
features = pd.read_csv('D:/DATOS/RELOADED/csv/exp_features.csv', 
                              low_memory= False)
kaggle_df = pd.read_csv('D:/DATOS/RELOADED/csv/trocafone_kaggle_test.csv', 
                              low_memory= False)

In [3]:
features.head()

,Unnamed: 0,person,cantidad de conversiones,cantidad de veces que vio un producto,cantidad de visitas a la pagina,cantidad de checkouts,visitaron el sitio entre las 13hs y 24hs,cantidad de vistas del J5,cantidad de vistas del iphone 5s,cantidad de vistas del samsung s6 flat,cantidad de vistas del iphone 6,cantidad de vistas del iphone 6s,cantidad de vistas entre semana
0,0,4886f805,NaN,4.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0
1,1,ad93850f,NaN,20.0,5.0,1.0,4.0,NaN,17.0,NaN,NaN,NaN,5.0
2,2,0297fc1e,NaN,404.0,95.0,7.0,64.0,NaN,1.0,NaN,213.0,213.0,81.0
3,3,2d681dd8,NaN,13.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0
4,4,cccea85e,NaN,739.0,22.0,1.0,18.0,NaN,2.0,1.0,NaN,NaN,20.0

In [4]:
# KNN no tolera NaN
features['cantidad de conversiones'].fillna(0, inplace=True)
features['cantidad de veces que vio un producto'].fillna(0, inplace=True)
features['cantidad de visitas a la pagina'].fillna(0, inplace=True)
features['cantidad de checkouts'].fillna(0, inplace=True)
features['visitaron el sitio entre las 13hs y 24hs'].fillna(0, inplace=True)
features['cantidad de vistas del J5'].fillna(0, inplace=True)
features['cantidad de vistas del iphone 5s'].fillna(0, inplace=True)
features['cantidad de vistas del samsung s6 flat'].fillna(0, inplace=True)
features['cantidad de vistas del iphone 6'].fillna(0, inplace=True)
features['cantidad de vistas del iphone 6s'].fillna(0, inplace=True)
features['cantidad de vistas entre semana'].fillna(0, inplace=True)

In [5]:
labels_training.head()

     person  label
0  0566e9c1      0
1  6ec7ee77      0
2  abe7a2fb      0
3  34728364      0
4  87ed62de      0

In [6]:
test_df = pd.merge(features, labels_training, how='inner', on='person')

In [45]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19414 entries, 0 to 19413
Data columns (total 14 columns):
Unnamed: 0                                  19414 non-null int64
person                                      19414 non-null object
cantidad de conversiones                    19414 non-null float64
cantidad de veces que vio un producto       19414 non-null float64
cantidad de visitas a la pagina             19414 non-null float64
cantidad de checkouts                       19414 non-null float64
visitaron el sitio entre las 13hs y 24hs    19414 non-null float64
cantidad de vistas del J5                   19414 non-null float64
cantidad de vistas del iphone 5s            19414 non-null float64
cantidad de vistas del samsung s6 flat      19414 non-null float64
cantidad de vistas del iphone 6             19414 non-null float64
cantidad de vistas del iphone 6s            19414 non-null float64
cantidad de vistas entre semana             19414 non-null float64
label                                       19414 non-null int64
dtypes: float64(11), int64(2), object(1)
memory usage: 2.2+ MB

### Evaluacion de KNN dividiendo el set de entrenamiento

In [69]:
# loading libraries

# X will have the numeric data, Y will have the target class
X = np.array(test_df.ix[:, 2:13]) 
y = np.array(test_df['label']) 

# Split into train and test, use only 10% as test (15 flowers)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=7500)

# Create KNN classifier
knn = KNeighborsClassifier(n_neighbors=4)

# FIT (this does nothing in normal KNN)
knn.fit(X_train, y_train)

# predict the response 
pred = knn.predict(X_test)

# evaluate accuracy
print(accuracy_score(y_test, pred))
# print(y_test)

c:\users\admin\appdata\local\programs\python\python36-64\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

0.9448879732165851

### Prediccion con K=4 (Tomado con pruebas simples)

In [43]:
pred_df = pd.merge(features, kaggle_df, how='inner', on='person')

In [44]:
pred_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19415 entries, 0 to 19414
Data columns (total 13 columns):
Unnamed: 0                                  19415 non-null int64
person                                      19415 non-null object
cantidad de conversiones                    19415 non-null float64
cantidad de veces que vio un producto       19415 non-null float64
cantidad de visitas a la pagina             19415 non-null float64
cantidad de checkouts                       19415 non-null float64
visitaron el sitio entre las 13hs y 24hs    19415 non-null float64
cantidad de vistas del J5                   19415 non-null float64
cantidad de vistas del iphone 5s            19415 non-null float64
cantidad de vistas del samsung s6 flat      19415 non-null float64
cantidad de vistas del iphone 6             19415 non-null float64
cantidad de vistas del iphone 6s            19415 non-null float64
cantidad de vistas entre semana             19415 non-null float64
dtypes: float64(11), int64(1), object(1)
memory usage: 2.1+ MB

In [72]:
# loading libraries

# X will have the numeric data, Y will have the target class
X_train = np.array(test_df.ix[:, 2:13]) 
y_train = np.array(test_df['label']) 
X_test = np.array(pred_df.ix[:, 2:13]) 

# Create KNN classifier
knn = KNeighborsRegressor(n_neighbors=4)

# FIT (this does nothing in normal KNN)
knn.fit(X_train, y_train)

# predict the response 
pred_df['label'] = knn.predict(X_test)
pred_df.head(20)

c:\users\admin\appdata\local\programs\python\python36-64\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.
c:\users\admin\appdata\local\programs\python\python36-64\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

,Unnamed: 0,person,cantidad de conversiones,cantidad de veces que vio un producto,cantidad de visitas a la pagina,cantidad de checkouts,visitaron el sitio entre las 13hs y 24hs,cantidad de vistas del J5,cantidad de vistas del iphone 5s,cantidad de vistas del samsung s6 flat,cantidad de vistas del iphone 6,cantidad de vistas del iphone 6s,cantidad de vistas entre semana,label
0,0,4886f805,0.0,4.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.00
1,2,0297fc1e,0.0,404.0,95.0,7.0,64.0,0.0,1.0,0.0,213.0,213.0,81.0,0.00
2,3,2d681dd8,0.0,13.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.25
3,4,cccea85e,0.0,739.0,22.0,1.0,18.0,0.0,2.0,1.0,0.0,0.0,20.0,0.00
4,5,4c8a8b93,0.0,177.0,20.0,2.0,13.0,0.0,21.0,0.0,83.0,83.0,10.0,0.00
5,7,29ebb414,0.0,8.0,4.0,1.0,4.0,0.0,0.0,0.0,1.0,1.0,2.0,0.00
6,11,3dc1950f,0.0,595.0,30.0,3.0,24.0,0.0,10.0,16.0,21.0,21.0,30.0,0.00
7,12,8ea4c165,0.0,97.0,7.0,3.0,6.0,3.0,0.0,9.0,0.0,0.0,4.0,0.00
8,14,d8cfe234,1.0,39.0,4.0,3.0,4.0,0.0,0.0,8.0,0.0,0.0,4.0,0.25
9,17,d6bc64df,0.0,155.0,7.0,2.0,2.0,0.0,18.0,0.0,8.0,8.0,4.0,0.00
10,18,ec9c4059,1.0,25.0,7.0,2.0,3.0,0.0,0.0,0.0,19.0,19.0,7.0,0.00
11,22,d21b8e6b,0.0,5.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
12,23,2a724d87,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.00
13,25,686c49c9,0.0,19.0,5.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,5.0,0.00
14,27,a08d42ea,1.0,41.0,5.0,1.0,4.0,0.0,0.0,8.0,0.0,0.0,4.0,0.00
15,32,c98f5cf1,1.0,104.0,41.0,4.0,30.0,4.0,0.0,2.0,0.0,0.0,29.0,0.00
16,34,d614c608,0.0,3.0,3.0,1.0,1.0,3.0,0.0,0.0,0.0,0.0,2.0,0.00
17,37,e45acd53,3.0,230.0,58.0,12.0,46.0,0.0,0.0,0.0,0.0,0.0,45.0,0.25
18,38,7d876393,0.0,229.0,18.0,3.0,10.0,0.0,27.0,18.0,23.0,23.0,11.0,0.00
19,39,f5af843f,0.0,94.0,11.0,3.0,7.0,1.0,17.0,3.0,22.0,22.0,8.0,0.25

### Armar el archivo de submit

In [74]:
out_df = pred_df[['person', 'label']]
out_df.set_index('person', inplace=True)
out_df.head()

          label
person
4886f805   0.00
0297fc1e   0.00
2d681dd8   0.25
cccea85e   0.00
4c8a8b93   0.00

In [75]:
out_df.to_csv('D:/DATOS/RELOADED/csv/submit.csv')